### ISSUE TITLE
raiseKeyError

### ISSUE THREAD

**Issue by sergey6661313** [KJ002/Muon#1]
![изображение](https://user-images.githubusercontent.com/16412693/210209735-3939e0fd-88b4-4c16-abc8-1a7233a7ed41.png)
("tables.nim" where this file?)

**Comment by jbutcher5** [comment]
My apologies, it seems I wrote this program with some pretty poor practices. You'll need to specify a repo (either `aur` or `void`). I understand this is convenient in every day use so maybe it should be added to a config file. I will discourage you from using the project as there are definitely better tools out there for you. (so to fix this just run `./muon zig -r aur` if you're on an arch based distro).
